version: "3.9"

networks:
  app-tier:
    driver: bridge
services:
  cmc_producer:
    container_name: cmc-producer
    image: "yawkar/cmc-producer"
    networks:
      - app-tier
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - PRODUCER_SOURCE=cmc
      - PRODUCER_SUBTHEME=cryptocurrency
      - CMC_API_KEY=203c08ca-cb50-4dd6-8d98-e74a23a2934d
    depends_on:
      - kafka

  cmc-filter:
    container_name: cmc-filter-container
    image: "yawkar/cmc-filter"
    networks:
      - app-tier
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - SPRING_KAFKA_CONSUMER_GROUP-ID=cmc-filters
    depends_on:
      - kafka

  cryptocurrency-loader:
    container_name: cryptocurrency-loader-container
    image: "yawkar/cryptocurrency-loader"
    networks:
      - app-tier
    environment:
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - SPRING_KAFKA_CONSUMER_GROUP-ID=cryptocurrency-loaders
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-container:5432/cryptocurrency
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - LOADER_SUBTHEME=cryptocurrency
    depends_on:
      - kafka
      - postgres

  zookeeper:
    container_name: zookeeper
    image: "bitnami/zookeeper:latest"
    networks:
      - app-tier
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    container_name: kafka
    image: "bitnami/kafka:latest"
    networks:
      - app-tier
    ports:
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  kafka-ui:
    container_name: kafka-ui
    image: "provectuslabs/kafka-ui"
    networks:
      - app-tier
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    restart: always
    depends_on:
      - kafka

  postgres:
    container_name: postgres-container
    image: postgres:14-alpine
    networks:
      - app-tier
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cryptocurrency
      
  db-migrations:
    container_name: liquibase-container
    image: yawkar/db-migrations
    networks:
      - app-tier
    environment:
      - DB_URL=postgres:5432
      - JDBC_URL=jdbc:postgresql://postgres:5432/cryptocurrency 
      - USERNAME=postgres  
      - PASSWORD=postgres
    links:
      - postgres
    depends_on:
      - postgres
    
    
    
