{
 "title": "HSE CourseWork",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cryptocurrencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BTC price in USD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "BTC", "legendFormat": "BTC" }
   ]
  },
  {
   "title": "Cryptocurrency loader load metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Kafka wait time in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "kafka_consumer_io_wait_time_ns_avg / 1000000000",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "JVM memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes / 1024 / 1024",
     "legendFormat": "{{id}} {{area}}"
    }
   ]
  },
  {
   "title": "System cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "{{__name__}} {{instance}}" }
   ]
  }
 ]
}