global:
  scrape_interval: 5m

scrape_configs:
  - job_name: 'coursework'
    scrape_interval: 5m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cryptocurrency-loader-container:8081']
