apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheuscoursework:10000
    access: proxy
    orgId: 1
    basicAuth: false
    isDefault: true
    editable: true
